// <auto-generated />
using System;
using ApiBasesDeDatosProyecto.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ApiBasesDeDatosProyecto.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20240909081903_paises")]
    partial class paises
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ApiBasesDeDatosProyecto.Entities.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Empleo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<int>("PaisId")
                        .HasColumnType("int");

                    b.Property<DateTime>("dateOfBirth")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PaisId");

                    b.ToTable("Clientes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Apellido = "Perez",
                            Email = "amin1@gmail.com",
                            Empleo = "Delincuente",
                            Nombre = "Juan",
                            PaisId = 1,
                            dateOfBirth = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            Apellido = "Lopez",
                            Email = "amin2@gmail.com",
                            Empleo = "Profesor",
                            Nombre = "Maria",
                            PaisId = 2,
                            dateOfBirth = new DateTime(1985, 5, 23, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            Apellido = "Gomez",
                            Email = "amin3@gmail.com",
                            Empleo = "Abogado",
                            Nombre = "Carlos",
                            PaisId = 3,
                            dateOfBirth = new DateTime(1978, 11, 12, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("ApiBasesDeDatosProyecto.Entities.Pais", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Divisa")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Iso")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Paises");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Divisa = "EUR",
                            Iso = "AD",
                            Nombre = "Andorra"
                        },
                        new
                        {
                            Id = 2,
                            Divisa = "AED",
                            Iso = "AE",
                            Nombre = "United Arab Emirates"
                        },
                        new
                        {
                            Id = 3,
                            Divisa = "AFN",
                            Iso = "AF",
                            Nombre = "Afghanistan"
                        },
                        new
                        {
                            Id = 4,
                            Divisa = "XCD",
                            Iso = "AG",
                            Nombre = "Antigua and Barbuda"
                        },
                        new
                        {
                            Id = 5,
                            Divisa = "XCD",
                            Iso = "AI",
                            Nombre = "Anguilla"
                        },
                        new
                        {
                            Id = 6,
                            Divisa = "ALL",
                            Iso = "AL",
                            Nombre = "Albania"
                        },
                        new
                        {
                            Id = 7,
                            Divisa = "AMD",
                            Iso = "AM",
                            Nombre = "Armenia"
                        },
                        new
                        {
                            Id = 8,
                            Divisa = "AOA",
                            Iso = "AO",
                            Nombre = "Angola"
                        },
                        new
                        {
                            Id = 9,
                            Divisa = "AND",
                            Iso = "AQ",
                            Nombre = "Antarctica"
                        },
                        new
                        {
                            Id = 10,
                            Divisa = "ARS",
                            Iso = "AR",
                            Nombre = "Argentina"
                        },
                        new
                        {
                            Id = 11,
                            Divisa = "EUR",
                            Iso = "BL",
                            Nombre = "Saint Barthélemy"
                        },
                        new
                        {
                            Id = 12,
                            Divisa = "BMD",
                            Iso = "BM",
                            Nombre = "Bermuda"
                        },
                        new
                        {
                            Id = 13,
                            Divisa = "BND",
                            Iso = "BN",
                            Nombre = "Brunei"
                        },
                        new
                        {
                            Id = 14,
                            Divisa = "BOB",
                            Iso = "BO",
                            Nombre = "Bolivia"
                        },
                        new
                        {
                            Id = 15,
                            Divisa = "USD",
                            Iso = "BQ",
                            Nombre = "Bonaire"
                        },
                        new
                        {
                            Id = 16,
                            Divisa = "BRL",
                            Iso = "BR",
                            Nombre = "Brazil"
                        },
                        new
                        {
                            Id = 17,
                            Divisa = "BSD",
                            Iso = "BS",
                            Nombre = "Bahamas"
                        },
                        new
                        {
                            Id = 18,
                            Divisa = "BTN",
                            Iso = "BT",
                            Nombre = "Bhutan"
                        },
                        new
                        {
                            Id = 19,
                            Divisa = "NOK",
                            Iso = "BV",
                            Nombre = "Bouvet Island"
                        },
                        new
                        {
                            Id = 20,
                            Divisa = "BWP",
                            Iso = "BW",
                            Nombre = "Botswana"
                        },
                        new
                        {
                            Id = 21,
                            Divisa = "BYR",
                            Iso = "BY",
                            Nombre = "Belarus"
                        },
                        new
                        {
                            Id = 22,
                            Divisa = "BZD",
                            Iso = "BZ",
                            Nombre = "Belize"
                        },
                        new
                        {
                            Id = 23,
                            Divisa = "CAD",
                            Iso = "CA",
                            Nombre = "Canada"
                        },
                        new
                        {
                            Id = 24,
                            Divisa = "AUD",
                            Iso = "CC",
                            Nombre = "Cocos [Keeling] Islands"
                        },
                        new
                        {
                            Id = 25,
                            Divisa = "CDF",
                            Iso = "CD",
                            Nombre = "Democratic Republic of the Congo"
                        },
                        new
                        {
                            Id = 26,
                            Divisa = "XAF",
                            Iso = "CF",
                            Nombre = "Central African Republic"
                        },
                        new
                        {
                            Id = 27,
                            Divisa = "XAF",
                            Iso = "CG",
                            Nombre = "Republic of the Congo"
                        },
                        new
                        {
                            Id = 28,
                            Divisa = "CHF",
                            Iso = "CH",
                            Nombre = "Switzerland"
                        },
                        new
                        {
                            Id = 29,
                            Divisa = "XOF",
                            Iso = "CI",
                            Nombre = "Ivory Coast"
                        },
                        new
                        {
                            Id = 30,
                            Divisa = "NZD",
                            Iso = "CK",
                            Nombre = "Cook Islands"
                        },
                        new
                        {
                            Id = 31,
                            Divisa = "CLP",
                            Iso = "CL",
                            Nombre = "Chile"
                        },
                        new
                        {
                            Id = 32,
                            Divisa = "XAF",
                            Iso = "CM",
                            Nombre = "Cameroon"
                        },
                        new
                        {
                            Id = 33,
                            Divisa = "CNY",
                            Iso = "CN",
                            Nombre = "China"
                        },
                        new
                        {
                            Id = 34,
                            Divisa = "COP",
                            Iso = "CO",
                            Nombre = "Colombia"
                        },
                        new
                        {
                            Id = 35,
                            Divisa = "CRC",
                            Iso = "CR",
                            Nombre = "Costa Rica"
                        },
                        new
                        {
                            Id = 36,
                            Divisa = "CUP",
                            Iso = "CU",
                            Nombre = "Cuba"
                        },
                        new
                        {
                            Id = 37,
                            Divisa = "CVE",
                            Iso = "CV",
                            Nombre = "Cape Verde"
                        },
                        new
                        {
                            Id = 38,
                            Divisa = "ANG",
                            Iso = "CW",
                            Nombre = "Curacao"
                        },
                        new
                        {
                            Id = 39,
                            Divisa = "AUD",
                            Iso = "CX",
                            Nombre = "Christmas Island"
                        },
                        new
                        {
                            Id = 40,
                            Divisa = "EUR",
                            Iso = "CY",
                            Nombre = "Cyprus"
                        },
                        new
                        {
                            Id = 41,
                            Divisa = "CZK",
                            Iso = "CZ",
                            Nombre = "Czechia"
                        },
                        new
                        {
                            Id = 42,
                            Divisa = "EUR",
                            Iso = "DE",
                            Nombre = "Germany"
                        },
                        new
                        {
                            Id = 43,
                            Divisa = "DJF",
                            Iso = "DJ",
                            Nombre = "Djibouti"
                        },
                        new
                        {
                            Id = 44,
                            Divisa = "DKK",
                            Iso = "DK",
                            Nombre = "Denmark"
                        },
                        new
                        {
                            Id = 45,
                            Divisa = "XCD",
                            Iso = "DM",
                            Nombre = "Dominica"
                        },
                        new
                        {
                            Id = 46,
                            Divisa = "DOP",
                            Iso = "DO",
                            Nombre = "Dominican Republic"
                        },
                        new
                        {
                            Id = 47,
                            Divisa = "DZD",
                            Iso = "DZ",
                            Nombre = "Algeria"
                        },
                        new
                        {
                            Id = 48,
                            Divisa = "USD",
                            Iso = "EC",
                            Nombre = "Ecuador"
                        },
                        new
                        {
                            Id = 49,
                            Divisa = "EUR",
                            Iso = "EE",
                            Nombre = "Estonia"
                        },
                        new
                        {
                            Id = 50,
                            Divisa = "EGP",
                            Iso = "EG",
                            Nombre = "Egypt"
                        },
                        new
                        {
                            Id = 51,
                            Divisa = "MAD",
                            Iso = "EH",
                            Nombre = "Western Sahara"
                        },
                        new
                        {
                            Id = 52,
                            Divisa = "ERN",
                            Iso = "ER",
                            Nombre = "Eritrea"
                        },
                        new
                        {
                            Id = 53,
                            Divisa = "EUR",
                            Iso = "ES",
                            Nombre = "Spain"
                        },
                        new
                        {
                            Id = 54,
                            Divisa = "ETB",
                            Iso = "ET",
                            Nombre = "Ethiopia"
                        },
                        new
                        {
                            Id = 55,
                            Divisa = "EUR",
                            Iso = "FI",
                            Nombre = "Finland"
                        },
                        new
                        {
                            Id = 56,
                            Divisa = "FJD",
                            Iso = "FJ",
                            Nombre = "Fiji"
                        },
                        new
                        {
                            Id = 57,
                            Divisa = "FKP",
                            Iso = "FK",
                            Nombre = "Falkland Islands"
                        },
                        new
                        {
                            Id = 58,
                            Divisa = "USD",
                            Iso = "FM",
                            Nombre = "Micronesia"
                        },
                        new
                        {
                            Id = 59,
                            Divisa = "DKK",
                            Iso = "FO",
                            Nombre = "Faroe Islands"
                        },
                        new
                        {
                            Id = 60,
                            Divisa = "EUR",
                            Iso = "FR",
                            Nombre = "France"
                        },
                        new
                        {
                            Id = 61,
                            Divisa = "XAF",
                            Iso = "GA",
                            Nombre = "Gabon"
                        },
                        new
                        {
                            Id = 62,
                            Divisa = "GBP",
                            Iso = "GB",
                            Nombre = "United Kingdom"
                        },
                        new
                        {
                            Id = 63,
                            Divisa = "XCD",
                            Iso = "GD",
                            Nombre = "Grenada"
                        },
                        new
                        {
                            Id = 64,
                            Divisa = "GEL",
                            Iso = "GE",
                            Nombre = "Georgia"
                        },
                        new
                        {
                            Id = 65,
                            Divisa = "EUR",
                            Iso = "GF",
                            Nombre = "French Guiana"
                        },
                        new
                        {
                            Id = 66,
                            Divisa = "GBP",
                            Iso = "GG",
                            Nombre = "Guernsey"
                        },
                        new
                        {
                            Id = 67,
                            Divisa = "GHS",
                            Iso = "GH",
                            Nombre = "Ghana"
                        },
                        new
                        {
                            Id = 68,
                            Divisa = "GIP",
                            Iso = "GI",
                            Nombre = "Gibraltar"
                        },
                        new
                        {
                            Id = 69,
                            Divisa = "DKK",
                            Iso = "GL",
                            Nombre = "Greenland"
                        },
                        new
                        {
                            Id = 70,
                            Divisa = "GMD",
                            Iso = "GM",
                            Nombre = "Gambia"
                        },
                        new
                        {
                            Id = 71,
                            Divisa = "GNF",
                            Iso = "GN",
                            Nombre = "Guinea"
                        },
                        new
                        {
                            Id = 72,
                            Divisa = "EUR",
                            Iso = "GP",
                            Nombre = "Guadeloupe"
                        },
                        new
                        {
                            Id = 73,
                            Divisa = "XAF",
                            Iso = "GQ",
                            Nombre = "Equatorial Guinea"
                        },
                        new
                        {
                            Id = 74,
                            Divisa = "EUR",
                            Iso = "GR",
                            Nombre = "Greece"
                        },
                        new
                        {
                            Id = 75,
                            Divisa = "GBP",
                            Iso = "GS",
                            Nombre = "South Georgia and the South Sandwich Islands"
                        },
                        new
                        {
                            Id = 76,
                            Divisa = "GTQ",
                            Iso = "GT",
                            Nombre = "Guatemala"
                        },
                        new
                        {
                            Id = 77,
                            Divisa = "USD",
                            Iso = "GU",
                            Nombre = "Guam"
                        },
                        new
                        {
                            Id = 78,
                            Divisa = "GYD",
                            Iso = "GY",
                            Nombre = "Guyana"
                        },
                        new
                        {
                            Id = 79,
                            Divisa = "HKD",
                            Iso = "HK",
                            Nombre = "Hong Kong"
                        },
                        new
                        {
                            Id = 80,
                            Divisa = "HNL",
                            Iso = "HN",
                            Nombre = "Honduras"
                        },
                        new
                        {
                            Id = 81,
                            Divisa = "HRK",
                            Iso = "HR",
                            Nombre = "Croatia"
                        },
                        new
                        {
                            Id = 82,
                            Divisa = "HTG",
                            Iso = "HT",
                            Nombre = "Haiti"
                        },
                        new
                        {
                            Id = 83,
                            Divisa = "HUF",
                            Iso = "HU",
                            Nombre = "Hungary"
                        },
                        new
                        {
                            Id = 84,
                            Divisa = "IDR",
                            Iso = "ID",
                            Nombre = "Indonesia"
                        },
                        new
                        {
                            Id = 85,
                            Divisa = "EUR",
                            Iso = "IE",
                            Nombre = "Ireland"
                        },
                        new
                        {
                            Id = 86,
                            Divisa = "ILS",
                            Iso = "IL",
                            Nombre = "Israel"
                        },
                        new
                        {
                            Id = 87,
                            Divisa = "GBP",
                            Iso = "IM",
                            Nombre = "Isle of Man"
                        },
                        new
                        {
                            Id = 88,
                            Divisa = "INR",
                            Iso = "IN",
                            Nombre = "India"
                        },
                        new
                        {
                            Id = 89,
                            Divisa = "USD",
                            Iso = "IO",
                            Nombre = "British Indian Ocean Territory"
                        },
                        new
                        {
                            Id = 90,
                            Divisa = "IQD",
                            Iso = "IQ",
                            Nombre = "Iraq"
                        },
                        new
                        {
                            Id = 91,
                            Divisa = "IRR",
                            Iso = "IR",
                            Nombre = "Iran"
                        },
                        new
                        {
                            Id = 92,
                            Divisa = "ISK",
                            Iso = "IS",
                            Nombre = "Iceland"
                        },
                        new
                        {
                            Id = 93,
                            Divisa = "EUR",
                            Iso = "IT",
                            Nombre = "Italy"
                        },
                        new
                        {
                            Id = 94,
                            Divisa = "GBP",
                            Iso = "JE",
                            Nombre = "Jersey"
                        },
                        new
                        {
                            Id = 95,
                            Divisa = "JMD",
                            Iso = "JM",
                            Nombre = "Jamaica"
                        },
                        new
                        {
                            Id = 96,
                            Divisa = "JOD",
                            Iso = "JO",
                            Nombre = "Jordan"
                        },
                        new
                        {
                            Id = 97,
                            Divisa = "JPY",
                            Iso = "JP",
                            Nombre = "Japan"
                        },
                        new
                        {
                            Id = 98,
                            Divisa = "KES",
                            Iso = "KE",
                            Nombre = "Kenya"
                        },
                        new
                        {
                            Id = 99,
                            Divisa = "KGS",
                            Iso = "KG",
                            Nombre = "Kyrgyzstan"
                        },
                        new
                        {
                            Id = 100,
                            Divisa = "KHR",
                            Iso = "KH",
                            Nombre = "Cambodia"
                        },
                        new
                        {
                            Id = 101,
                            Divisa = "AUD",
                            Iso = "KI",
                            Nombre = "Kiribati"
                        },
                        new
                        {
                            Id = 102,
                            Divisa = "KMF",
                            Iso = "KM",
                            Nombre = "Comoros"
                        },
                        new
                        {
                            Id = 103,
                            Divisa = "XCD",
                            Iso = "KN",
                            Nombre = "Saint Kitts and Nevis"
                        },
                        new
                        {
                            Id = 104,
                            Divisa = "KPW",
                            Iso = "KP",
                            Nombre = "North Korea"
                        },
                        new
                        {
                            Id = 105,
                            Divisa = "KRW",
                            Iso = "KR",
                            Nombre = "South Korea"
                        },
                        new
                        {
                            Id = 106,
                            Divisa = "KWD",
                            Iso = "KW",
                            Nombre = "Kuwait"
                        },
                        new
                        {
                            Id = 107,
                            Divisa = "KYD",
                            Iso = "KY",
                            Nombre = "Cayman Islands"
                        },
                        new
                        {
                            Id = 108,
                            Divisa = "KZT",
                            Iso = "KZ",
                            Nombre = "Kazakhstan"
                        },
                        new
                        {
                            Id = 109,
                            Divisa = "LAK",
                            Iso = "LA",
                            Nombre = "Laos"
                        },
                        new
                        {
                            Id = 110,
                            Divisa = "LBP",
                            Iso = "LB",
                            Nombre = "Lebanon"
                        },
                        new
                        {
                            Id = 111,
                            Divisa = "XCD",
                            Iso = "LC",
                            Nombre = "Saint Lucia"
                        },
                        new
                        {
                            Id = 112,
                            Divisa = "CHF",
                            Iso = "LI",
                            Nombre = "Liechtenstein"
                        },
                        new
                        {
                            Id = 113,
                            Divisa = "LKR",
                            Iso = "LK",
                            Nombre = "Sri Lanka"
                        },
                        new
                        {
                            Id = 114,
                            Divisa = "LRD",
                            Iso = "LR",
                            Nombre = "Liberia"
                        },
                        new
                        {
                            Id = 115,
                            Divisa = "LSL",
                            Iso = "LS",
                            Nombre = "Lesotho"
                        },
                        new
                        {
                            Id = 116,
                            Divisa = "EUR",
                            Iso = "LT",
                            Nombre = "Lithuania"
                        },
                        new
                        {
                            Id = 117,
                            Divisa = "EUR",
                            Iso = "LU",
                            Nombre = "Luxembourg"
                        },
                        new
                        {
                            Id = 118,
                            Divisa = "EUR",
                            Iso = "LV",
                            Nombre = "Latvia"
                        },
                        new
                        {
                            Id = 119,
                            Divisa = "MAD",
                            Iso = "MA",
                            Nombre = "Morocco"
                        },
                        new
                        {
                            Id = 120,
                            Divisa = "EUR",
                            Iso = "MC",
                            Nombre = "Monaco"
                        },
                        new
                        {
                            Id = 121,
                            Divisa = "MDL",
                            Iso = "MD",
                            Nombre = "Moldova"
                        },
                        new
                        {
                            Id = 122,
                            Divisa = "EUR",
                            Iso = "ME",
                            Nombre = "Montenegro"
                        },
                        new
                        {
                            Id = 123,
                            Divisa = "EUR",
                            Iso = "MF",
                            Nombre = "Saint Martin"
                        },
                        new
                        {
                            Id = 124,
                            Divisa = "MGA",
                            Iso = "MG",
                            Nombre = "Madagascar"
                        },
                        new
                        {
                            Id = 125,
                            Divisa = "USD",
                            Iso = "MH",
                            Nombre = "Marshall Islands"
                        },
                        new
                        {
                            Id = 126,
                            Divisa = "MKD",
                            Iso = "MK",
                            Nombre = "North Macedonia"
                        },
                        new
                        {
                            Id = 127,
                            Divisa = "XOF",
                            Iso = "ML",
                            Nombre = "Mali"
                        },
                        new
                        {
                            Id = 128,
                            Divisa = "MMK",
                            Iso = "MM",
                            Nombre = "Myanmar"
                        },
                        new
                        {
                            Id = 129,
                            Divisa = "MNT",
                            Iso = "MN",
                            Nombre = "Mongolia"
                        },
                        new
                        {
                            Id = 130,
                            Divisa = "MOP",
                            Iso = "MO",
                            Nombre = "Macao"
                        },
                        new
                        {
                            Id = 131,
                            Divisa = "USD",
                            Iso = "MP",
                            Nombre = "Northern Mariana Islands"
                        },
                        new
                        {
                            Id = 132,
                            Divisa = "EUR",
                            Iso = "MQ",
                            Nombre = "Martinique"
                        },
                        new
                        {
                            Id = 133,
                            Divisa = "MRU",
                            Iso = "MR",
                            Nombre = "Mauritania"
                        },
                        new
                        {
                            Id = 134,
                            Divisa = "XCD",
                            Iso = "MS",
                            Nombre = "Montserrat"
                        },
                        new
                        {
                            Id = 135,
                            Divisa = "EUR",
                            Iso = "MT",
                            Nombre = "Malta"
                        },
                        new
                        {
                            Id = 136,
                            Divisa = "MUR",
                            Iso = "MU",
                            Nombre = "Mauritius"
                        },
                        new
                        {
                            Id = 137,
                            Divisa = "MWK",
                            Iso = "MW",
                            Nombre = "Malawi"
                        },
                        new
                        {
                            Id = 138,
                            Divisa = "MXN",
                            Iso = "MX",
                            Nombre = "Mexico"
                        },
                        new
                        {
                            Id = 139,
                            Divisa = "MYR",
                            Iso = "MY",
                            Nombre = "Malaysia"
                        },
                        new
                        {
                            Id = 140,
                            Divisa = "MZN",
                            Iso = "MZ",
                            Nombre = "Mozambique"
                        },
                        new
                        {
                            Id = 141,
                            Divisa = "NAD",
                            Iso = "NA",
                            Nombre = "Namibia"
                        },
                        new
                        {
                            Id = 142,
                            Divisa = "XPF",
                            Iso = "NC",
                            Nombre = "New Caledonia"
                        },
                        new
                        {
                            Id = 143,
                            Divisa = "XOF",
                            Iso = "NE",
                            Nombre = "Niger"
                        },
                        new
                        {
                            Id = 144,
                            Divisa = "AUD",
                            Iso = "NF",
                            Nombre = "Norfolk Island"
                        },
                        new
                        {
                            Id = 145,
                            Divisa = "NGN",
                            Iso = "NG",
                            Nombre = "Nigeria"
                        },
                        new
                        {
                            Id = 146,
                            Divisa = "NIO",
                            Iso = "NI",
                            Nombre = "Nicaragua"
                        },
                        new
                        {
                            Id = 147,
                            Divisa = "EUR",
                            Iso = "NL",
                            Nombre = "Netherlands"
                        },
                        new
                        {
                            Id = 148,
                            Divisa = "NOK",
                            Iso = "NO",
                            Nombre = "Norway"
                        },
                        new
                        {
                            Id = 149,
                            Divisa = "NPR",
                            Iso = "NP",
                            Nombre = "Nepal"
                        },
                        new
                        {
                            Id = 150,
                            Divisa = "AUD",
                            Iso = "NR",
                            Nombre = "Nauru"
                        },
                        new
                        {
                            Id = 151,
                            Divisa = "NZD",
                            Iso = "NU",
                            Nombre = "Niue"
                        },
                        new
                        {
                            Id = 152,
                            Divisa = "NZD",
                            Iso = "NZ",
                            Nombre = "New Zealand"
                        },
                        new
                        {
                            Id = 153,
                            Divisa = "OMR",
                            Iso = "OM",
                            Nombre = "Oman"
                        },
                        new
                        {
                            Id = 154,
                            Divisa = "PAB",
                            Iso = "PA",
                            Nombre = "Panama"
                        },
                        new
                        {
                            Id = 155,
                            Divisa = "PEN",
                            Iso = "PE",
                            Nombre = "Peru"
                        },
                        new
                        {
                            Id = 156,
                            Divisa = "XPF",
                            Iso = "PF",
                            Nombre = "French Polynesia"
                        },
                        new
                        {
                            Id = 157,
                            Divisa = "PGK",
                            Iso = "PG",
                            Nombre = "Papua New Guinea"
                        },
                        new
                        {
                            Id = 158,
                            Divisa = "PHP",
                            Iso = "PH",
                            Nombre = "Philippines"
                        },
                        new
                        {
                            Id = 159,
                            Divisa = "PKR",
                            Iso = "PK",
                            Nombre = "Pakistan"
                        },
                        new
                        {
                            Id = 160,
                            Divisa = "PLN",
                            Iso = "PL",
                            Nombre = "Poland"
                        },
                        new
                        {
                            Id = 161,
                            Divisa = "EUR",
                            Iso = "PM",
                            Nombre = "Saint Pierre and Miquelon"
                        },
                        new
                        {
                            Id = 162,
                            Divisa = "NZD",
                            Iso = "PN",
                            Nombre = "Pitcairn Islands"
                        },
                        new
                        {
                            Id = 163,
                            Divisa = "EUR",
                            Iso = "PT",
                            Nombre = "Portugal"
                        },
                        new
                        {
                            Id = 164,
                            Divisa = "ILS",
                            Iso = "PS",
                            Nombre = "Palestine"
                        },
                        new
                        {
                            Id = 165,
                            Divisa = "USD",
                            Iso = "PR",
                            Nombre = "Puerto Rico"
                        },
                        new
                        {
                            Id = 166,
                            Divisa = "QAR",
                            Iso = "QA",
                            Nombre = "Qatar"
                        },
                        new
                        {
                            Id = 167,
                            Divisa = "EUR",
                            Iso = "RE",
                            Nombre = "Réunion"
                        },
                        new
                        {
                            Id = 168,
                            Divisa = "RON",
                            Iso = "RO",
                            Nombre = "Romania"
                        },
                        new
                        {
                            Id = 169,
                            Divisa = "RUB",
                            Iso = "RU",
                            Nombre = "Russia"
                        },
                        new
                        {
                            Id = 170,
                            Divisa = "RWF",
                            Iso = "RW",
                            Nombre = "Rwanda"
                        },
                        new
                        {
                            Id = 171,
                            Divisa = "SAR",
                            Iso = "SA",
                            Nombre = "Saudi Arabia"
                        },
                        new
                        {
                            Id = 172,
                            Divisa = "SBD",
                            Iso = "SB",
                            Nombre = "Solomon Islands"
                        },
                        new
                        {
                            Id = 173,
                            Divisa = "SCR",
                            Iso = "SC",
                            Nombre = "Seychelles"
                        },
                        new
                        {
                            Id = 174,
                            Divisa = "SDG",
                            Iso = "SD",
                            Nombre = "Sudan"
                        },
                        new
                        {
                            Id = 175,
                            Divisa = "SEK",
                            Iso = "SE",
                            Nombre = "Sweden"
                        },
                        new
                        {
                            Id = 176,
                            Divisa = "SGD",
                            Iso = "SG",
                            Nombre = "Singapore"
                        },
                        new
                        {
                            Id = 177,
                            Divisa = "SHP",
                            Iso = "SH",
                            Nombre = "Saint Helena"
                        },
                        new
                        {
                            Id = 178,
                            Divisa = "EUR",
                            Iso = "SI",
                            Nombre = "Slovenia"
                        },
                        new
                        {
                            Id = 179,
                            Divisa = "NOK",
                            Iso = "SJ",
                            Nombre = "Svalbard and Jan Mayen"
                        },
                        new
                        {
                            Id = 180,
                            Divisa = "EUR",
                            Iso = "SK",
                            Nombre = "Slovakia"
                        },
                        new
                        {
                            Id = 181,
                            Divisa = "SLL",
                            Iso = "SL",
                            Nombre = "Sierra Leone"
                        },
                        new
                        {
                            Id = 182,
                            Divisa = "EUR",
                            Iso = "SM",
                            Nombre = "San Marino"
                        },
                        new
                        {
                            Id = 183,
                            Divisa = "SOS",
                            Iso = "SO",
                            Nombre = "Somalia"
                        },
                        new
                        {
                            Id = 184,
                            Divisa = "SRD",
                            Iso = "SR",
                            Nombre = "Suriname"
                        },
                        new
                        {
                            Id = 185,
                            Divisa = "SSP",
                            Iso = "SS",
                            Nombre = "South Sudan"
                        },
                        new
                        {
                            Id = 186,
                            Divisa = "STN",
                            Iso = "ST",
                            Nombre = "Sao Tome and Principe"
                        },
                        new
                        {
                            Id = 187,
                            Divisa = "USD",
                            Iso = "SV",
                            Nombre = "El Salvador"
                        },
                        new
                        {
                            Id = 188,
                            Divisa = "ANG",
                            Iso = "SX",
                            Nombre = "Sint Maarten"
                        },
                        new
                        {
                            Id = 189,
                            Divisa = "SYP",
                            Iso = "SY",
                            Nombre = "Syria"
                        },
                        new
                        {
                            Id = 190,
                            Divisa = "SZL",
                            Iso = "SZ",
                            Nombre = "Eswatini"
                        },
                        new
                        {
                            Id = 191,
                            Divisa = "USD",
                            Iso = "TC",
                            Nombre = "Turks and Caicos Islands"
                        },
                        new
                        {
                            Id = 192,
                            Divisa = "XAF",
                            Iso = "TD",
                            Nombre = "Chad"
                        },
                        new
                        {
                            Id = 193,
                            Divisa = "EUR",
                            Iso = "TF",
                            Nombre = "French Southern Territories"
                        },
                        new
                        {
                            Id = 194,
                            Divisa = "XOF",
                            Iso = "TG",
                            Nombre = "Togo"
                        },
                        new
                        {
                            Id = 195,
                            Divisa = "THB",
                            Iso = "TH",
                            Nombre = "Thailand"
                        },
                        new
                        {
                            Id = 196,
                            Divisa = "USD",
                            Iso = "TL",
                            Nombre = "Timor-Leste"
                        },
                        new
                        {
                            Id = 197,
                            Divisa = "TOP",
                            Iso = "TO",
                            Nombre = "Tonga"
                        },
                        new
                        {
                            Id = 198,
                            Divisa = "TTD",
                            Iso = "TT",
                            Nombre = "Trinidad and Tobago"
                        },
                        new
                        {
                            Id = 199,
                            Divisa = "TND",
                            Iso = "TN",
                            Nombre = "Tunisia"
                        },
                        new
                        {
                            Id = 200,
                            Divisa = "TRY",
                            Iso = "TR",
                            Nombre = "Turkey"
                        },
                        new
                        {
                            Id = 201,
                            Divisa = "TWD",
                            Iso = "TW",
                            Nombre = "Taiwan"
                        },
                        new
                        {
                            Id = 202,
                            Divisa = "TZS",
                            Iso = "TZ",
                            Nombre = "Tanzania"
                        },
                        new
                        {
                            Id = 203,
                            Divisa = "UAH",
                            Iso = "UA",
                            Nombre = "Ukraine"
                        },
                        new
                        {
                            Id = 204,
                            Divisa = "UGX",
                            Iso = "UG",
                            Nombre = "Uganda"
                        },
                        new
                        {
                            Id = 205,
                            Divisa = "USD",
                            Iso = "UM",
                            Nombre = "United States Minor Outlying Islands"
                        },
                        new
                        {
                            Id = 206,
                            Divisa = "USD",
                            Iso = "US",
                            Nombre = "United States"
                        },
                        new
                        {
                            Id = 207,
                            Divisa = "UYU",
                            Iso = "UY",
                            Nombre = "Uruguay"
                        },
                        new
                        {
                            Id = 208,
                            Divisa = "UZS",
                            Iso = "UZ",
                            Nombre = "Uzbekistan"
                        },
                        new
                        {
                            Id = 209,
                            Divisa = "EUR",
                            Iso = "VA",
                            Nombre = "Vatican City"
                        },
                        new
                        {
                            Id = 210,
                            Divisa = "XCD",
                            Iso = "VC",
                            Nombre = "Saint Vincent and the Grenadines"
                        },
                        new
                        {
                            Id = 211,
                            Divisa = "VES",
                            Iso = "VE",
                            Nombre = "Venezuela"
                        },
                        new
                        {
                            Id = 212,
                            Divisa = "USD",
                            Iso = "VG",
                            Nombre = "British Virgin Islands"
                        },
                        new
                        {
                            Id = 213,
                            Divisa = "USD",
                            Iso = "VI",
                            Nombre = "United States Virgin Islands"
                        },
                        new
                        {
                            Id = 214,
                            Divisa = "VND",
                            Iso = "VN",
                            Nombre = "Vietnam"
                        },
                        new
                        {
                            Id = 215,
                            Divisa = "VUV",
                            Iso = "VU",
                            Nombre = "Vanuatu"
                        },
                        new
                        {
                            Id = 216,
                            Divisa = "XPF",
                            Iso = "WF",
                            Nombre = "Wallis and Futuna"
                        },
                        new
                        {
                            Id = 217,
                            Divisa = "WST",
                            Iso = "WS",
                            Nombre = "Samoa"
                        },
                        new
                        {
                            Id = 218,
                            Divisa = "YER",
                            Iso = "YE",
                            Nombre = "Yemen"
                        },
                        new
                        {
                            Id = 219,
                            Divisa = "ZAR",
                            Iso = "ZA",
                            Nombre = "South Africa"
                        },
                        new
                        {
                            Id = 220,
                            Divisa = "ZMW",
                            Iso = "ZM",
                            Nombre = "Zambia"
                        },
                        new
                        {
                            Id = 221,
                            Divisa = "ZWL",
                            Iso = "ZW",
                            Nombre = "Zimbabwe"
                        });
                });

            modelBuilder.Entity("ApiBasesDeDatosProyecto.Entities.VistaClientesPaises", b =>
                {
                    b.Property<string>("ClienteApellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<string>("ClienteNombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Divisa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Empleo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Iso3")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PaisId")
                        .HasColumnType("int");

                    b.Property<string>("PaisNombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable((string)null);

                    b.ToView("VistaClientesPaises", (string)null);
                });

            modelBuilder.Entity("ApiBasesDeDatosProyecto.Models.AccessMonitoringData", b =>
                {
                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Empleo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaRecibido")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pais")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PaisId")
                        .HasColumnType("int");

                    b.Property<string>("TipoAcceso")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Usuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Email");

                    b.ToTable("AccessMonitoringDatas");
                });

            modelBuilder.Entity("ApiBasesDeDatosProyecto.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("Rol")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("ApiBasesDeDatosProyecto.Models.MonitoringData", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ClienteDestino")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClienteOrigen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaisDestino")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaisOrigen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<double>("ValorDestino")
                        .HasColumnType("float");

                    b.Property<double>("ValorOrigen")
                        .HasColumnType("float");

                    b.HasKey("Name");

                    b.ToTable("MonitoringDatas");
                });

            modelBuilder.Entity("ApiBasesDeDatosProyecto.Models.ProAlmClientePorPaisDto", b =>
                {
                    b.Property<int>("ClienteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClienteId"));

                    b.Property<string>("ClienteApellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClienteNombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Divisa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Empleo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Iso3")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PaisId")
                        .HasColumnType("int");

                    b.Property<string>("PaisNombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ClienteId");

                    b.ToTable("ProAlmClientePorPaisDtos");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("ApiBasesDeDatosProyecto.Entities.Cliente", b =>
                {
                    b.HasOne("ApiBasesDeDatosProyecto.Entities.Pais", "Pais")
                        .WithMany("Clientes")
                        .HasForeignKey("PaisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pais");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("ApiBasesDeDatosProyecto.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("ApiBasesDeDatosProyecto.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApiBasesDeDatosProyecto.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("ApiBasesDeDatosProyecto.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ApiBasesDeDatosProyecto.Entities.Pais", b =>
                {
                    b.Navigation("Clientes");
                });
#pragma warning restore 612, 618
        }
    }
}
