using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;
using ApiBasesDeDatosProyecto.Models; // Asegúrate de agregar este using

namespace ApiBasesDeDatosProyecto.Context
{
    public class Contexto : IdentityDbContext<ApplicationUser>
    {
        public DbSet<Cliente> Clientes { get; set; }
        public DbSet<Pais> Paises { get; set; }
        public DbSet<VistaClientesPaises> VistaClientesPaises { get; set; }
        public DbSet<ProAlmClientePorPaisDto> ProAlmClientePorPaisDtos { get; set; }
        public DbSet<MonitoringData> MonitoringDatas { get; set; }  // Agregar esta línea
        public DbSet<AccessMonitoringData> AccessMonitoringDatas { get; set; }

        public Contexto(DbContextOptions<Contexto> options) : base(options) { }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseLoggerFactory(LoggerFactory.Create(builder => builder.AddDebug()));
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            base.OnModelCreating(modelBuilder);

            modelBuilder.Entity<Pais>().HasData(
                new Pais { Id = 1, Nombre = "Andorra", Divisa = "EUR", Iso = "AD" },
    new Pais { Id = 2, Nombre = "United Arab Emirates", Divisa = "AED", Iso = "AE" },
    new Pais { Id = 3, Nombre = "Afghanistan", Divisa = "AFN", Iso = "AF" },
    new Pais { Id = 4, Nombre = "Antigua and Barbuda", Divisa = "XCD", Iso = "AG" },
    new Pais { Id = 5, Nombre = "Anguilla", Divisa = "XCD", Iso = "AI" },
    new Pais { Id = 6, Nombre = "Albania", Divisa = "ALL", Iso = "AL" },
    new Pais { Id = 7, Nombre = "Armenia", Divisa = "AMD", Iso = "AM" },
    new Pais { Id = 8, Nombre = "Angola", Divisa = "AOA", Iso = "AO" },
    new Pais { Id = 9, Nombre = "Antarctica", Divisa = "AND", Iso = "AQ" },
    new Pais { Id = 10, Nombre = "Argentina", Divisa = "ARS", Iso = "AR" },
    new Pais { Id = 11, Nombre = "Saint Barthélemy", Divisa = "EUR", Iso = "BL" },
    new Pais { Id = 12, Nombre = "Bermuda", Divisa = "BMD", Iso = "BM" },
    new Pais { Id = 13, Nombre = "Brunei", Divisa = "BND", Iso = "BN" },
    new Pais { Id = 14, Nombre = "Bolivia", Divisa = "BOB", Iso = "BO" },
    new Pais { Id = 15, Nombre = "Bonaire", Divisa = "USD", Iso = "BQ" },
    new Pais { Id = 16, Nombre = "Brazil", Divisa = "BRL", Iso = "BR" },
    new Pais { Id = 17, Nombre = "Bahamas", Divisa = "BSD", Iso = "BS" },
    new Pais { Id = 18, Nombre = "Bhutan", Divisa = "BTN", Iso = "BT" },
    new Pais { Id = 19, Nombre = "Bouvet Island", Divisa = "NOK", Iso = "BV" },
    new Pais { Id = 20, Nombre = "Botswana", Divisa = "BWP", Iso = "BW" },
    new Pais { Id = 21, Nombre = "Belarus", Divisa = "BYR", Iso = "BY" },
    new Pais { Id = 22, Nombre = "Belize", Divisa = "BZD", Iso = "BZ" },
    new Pais { Id = 23, Nombre = "Canada", Divisa = "CAD", Iso = "CA" },
    new Pais { Id = 24, Nombre = "Cocos [Keeling] Islands", Divisa = "AUD", Iso = "CC" },
    new Pais { Id = 25, Nombre = "Democratic Republic of the Congo", Divisa = "CDF", Iso = "CD" },
    new Pais { Id = 26, Nombre = "Central African Republic", Divisa = "XAF", Iso = "CF" },
    new Pais { Id = 27, Nombre = "Republic of the Congo", Divisa = "XAF", Iso = "CG" },
    new Pais { Id = 28, Nombre = "Switzerland", Divisa = "CHF", Iso = "CH" },
    new Pais { Id = 29, Nombre = "Ivory Coast", Divisa = "XOF", Iso = "CI" },
    new Pais { Id = 30, Nombre = "Cook Islands", Divisa = "NZD", Iso = "CK" },
    new Pais { Id = 31, Nombre = "Chile", Divisa = "CLP", Iso = "CL" },
    new Pais { Id = 32, Nombre = "Cameroon", Divisa = "XAF", Iso = "CM" },
    new Pais { Id = 33, Nombre = "China", Divisa = "CNY", Iso = "CN" },
    new Pais { Id = 34, Nombre = "Colombia", Divisa = "COP", Iso = "CO" },
    new Pais { Id = 35, Nombre = "Costa Rica", Divisa = "CRC", Iso = "CR" },
    new Pais { Id = 36, Nombre = "Cuba", Divisa = "CUP", Iso = "CU" },
    new Pais { Id = 37, Nombre = "Cape Verde", Divisa = "CVE", Iso = "CV" },
    new Pais { Id = 38, Nombre = "Curacao", Divisa = "ANG", Iso = "CW" },
    new Pais { Id = 39, Nombre = "Christmas Island", Divisa = "AUD", Iso = "CX" },
    new Pais { Id = 40, Nombre = "Cyprus", Divisa = "EUR", Iso = "CY" },
    new Pais { Id = 41, Nombre = "Czechia", Divisa = "CZK", Iso = "CZ" },
    new Pais { Id = 42, Nombre = "Germany", Divisa = "EUR", Iso = "DE" },
    new Pais { Id = 43, Nombre = "Djibouti", Divisa = "DJF", Iso = "DJ" },
    new Pais { Id = 44, Nombre = "Denmark", Divisa = "DKK", Iso = "DK" },
    new Pais { Id = 45, Nombre = "Dominica", Divisa = "XCD", Iso = "DM" },
    new Pais { Id = 46, Nombre = "Dominican Republic", Divisa = "DOP", Iso = "DO" },
    new Pais { Id = 47, Nombre = "Algeria", Divisa = "DZD", Iso = "DZ" },
    new Pais { Id = 48, Nombre = "Ecuador", Divisa = "USD", Iso = "EC" },
    new Pais { Id = 49, Nombre = "Estonia", Divisa = "EUR", Iso = "EE" },
    new Pais { Id = 50, Nombre = "Egypt", Divisa = "EGP", Iso = "EG" },
    new Pais { Id = 51, Nombre = "Western Sahara", Divisa = "MAD", Iso = "EH" },
    new Pais { Id = 52, Nombre = "Eritrea", Divisa = "ERN", Iso = "ER" },
    new Pais { Id = 53, Nombre = "Spain", Divisa = "EUR", Iso = "ES" },
    new Pais { Id = 54, Nombre = "Ethiopia", Divisa = "ETB", Iso = "ET" },
    new Pais { Id = 55, Nombre = "Finland", Divisa = "EUR", Iso = "FI" },
    new Pais { Id = 56, Nombre = "Fiji", Divisa = "FJD", Iso = "FJ" },
    new Pais { Id = 57, Nombre = "Falkland Islands", Divisa = "FKP", Iso = "FK" },
    new Pais { Id = 58, Nombre = "Micronesia", Divisa = "USD", Iso = "FM" },
    new Pais { Id = 59, Nombre = "Faroe Islands", Divisa = "DKK", Iso = "FO" },
    new Pais { Id = 60, Nombre = "France", Divisa = "EUR", Iso = "FR" },
    new Pais { Id = 61, Nombre = "Gabon", Divisa = "XAF", Iso = "GA" },
    new Pais { Id = 62, Nombre = "United Kingdom", Divisa = "GBP", Iso = "GB" },
    new Pais { Id = 63, Nombre = "Grenada", Divisa = "XCD", Iso = "GD" },
    new Pais { Id = 64, Nombre = "Georgia", Divisa = "GEL", Iso = "GE" },
    new Pais { Id = 65, Nombre = "French Guiana", Divisa = "EUR", Iso = "GF" },
    new Pais { Id = 66, Nombre = "Guernsey", Divisa = "GBP", Iso = "GG" },
    new Pais { Id = 67, Nombre = "Ghana", Divisa = "GHS", Iso = "GH" },
    new Pais { Id = 68, Nombre = "Gibraltar", Divisa = "GIP", Iso = "GI" },
    new Pais { Id = 69, Nombre = "Greenland", Divisa = "DKK", Iso = "GL" },
    new Pais { Id = 70, Nombre = "Gambia", Divisa = "GMD", Iso = "GM" },
    new Pais { Id = 71, Nombre = "Guinea", Divisa = "GNF", Iso = "GN" },
    new Pais { Id = 72, Nombre = "Guadeloupe", Divisa = "EUR", Iso = "GP" },
    new Pais { Id = 73, Nombre = "Equatorial Guinea", Divisa = "XAF", Iso = "GQ" },
    new Pais { Id = 74, Nombre = "Greece", Divisa = "EUR", Iso = "GR" },
    new Pais { Id = 75, Nombre = "South Georgia and the South Sandwich Islands", Divisa = "GBP", Iso = "GS" },
    new Pais { Id = 76, Nombre = "Guatemala", Divisa = "GTQ", Iso = "GT" },
    new Pais { Id = 77, Nombre = "Guam", Divisa = "USD", Iso = "GU" },
    new Pais { Id = 78, Nombre = "Guyana", Divisa = "GYD", Iso = "GY" },
    new Pais { Id = 79, Nombre = "Hong Kong", Divisa = "HKD", Iso = "HK" },
    new Pais { Id = 80, Nombre = "Honduras", Divisa = "HNL", Iso = "HN" },
    new Pais { Id = 81, Nombre = "Croatia", Divisa = "HRK", Iso = "HR" },
    new Pais { Id = 82, Nombre = "Haiti", Divisa = "HTG", Iso = "HT" },
    new Pais { Id = 83, Nombre = "Hungary", Divisa = "HUF", Iso = "HU" },
    new Pais { Id = 84, Nombre = "Indonesia", Divisa = "IDR", Iso = "ID" },
    new Pais { Id = 85, Nombre = "Ireland", Divisa = "EUR", Iso = "IE" },
    new Pais { Id = 86, Nombre = "Israel", Divisa = "ILS", Iso = "IL" },
    new Pais { Id = 87, Nombre = "Isle of Man", Divisa = "GBP", Iso = "IM" },
    new Pais { Id = 88, Nombre = "India", Divisa = "INR", Iso = "IN" },
    new Pais { Id = 89, Nombre = "British Indian Ocean Territory", Divisa = "USD", Iso = "IO" },
    new Pais { Id = 90, Nombre = "Iraq", Divisa = "IQD", Iso = "IQ" },
    new Pais { Id = 91, Nombre = "Iran", Divisa = "IRR", Iso = "IR" },
    new Pais { Id = 92, Nombre = "Iceland", Divisa = "ISK", Iso = "IS" },
    new Pais { Id = 93, Nombre = "Italy", Divisa = "EUR", Iso = "IT" },
    new Pais { Id = 94, Nombre = "Jersey", Divisa = "GBP", Iso = "JE" },
    new Pais { Id = 95, Nombre = "Jamaica", Divisa = "JMD", Iso = "JM" },
    new Pais { Id = 96, Nombre = "Jordan", Divisa = "JOD", Iso = "JO" },
    new Pais { Id = 97, Nombre = "Japan", Divisa = "JPY", Iso = "JP" },
    new Pais { Id = 98, Nombre = "Kenya", Divisa = "KES", Iso = "KE" },
    new Pais { Id = 99, Nombre = "Kyrgyzstan", Divisa = "KGS", Iso = "KG" },
    new Pais { Id = 100, Nombre = "Cambodia", Divisa = "KHR", Iso = "KH" },
    new Pais { Id = 101, Nombre = "Kiribati", Divisa = "AUD", Iso = "KI" },
    new Pais { Id = 102, Nombre = "Comoros", Divisa = "KMF", Iso = "KM" },
    new Pais { Id = 103, Nombre = "Saint Kitts and Nevis", Divisa = "XCD", Iso = "KN" },
    new Pais { Id = 104, Nombre = "North Korea", Divisa = "KPW", Iso = "KP" },
    new Pais { Id = 105, Nombre = "South Korea", Divisa = "KRW", Iso = "KR" },
    new Pais { Id = 106, Nombre = "Kuwait", Divisa = "KWD", Iso = "KW" },
    new Pais { Id = 107, Nombre = "Cayman Islands", Divisa = "KYD", Iso = "KY" },
    new Pais { Id = 108, Nombre = "Kazakhstan", Divisa = "KZT", Iso = "KZ" },
    new Pais { Id = 109, Nombre = "Laos", Divisa = "LAK", Iso = "LA" },
    new Pais { Id = 110, Nombre = "Lebanon", Divisa = "LBP", Iso = "LB" },
    new Pais { Id = 111, Nombre = "Saint Lucia", Divisa = "XCD", Iso = "LC" },
    new Pais { Id = 112, Nombre = "Liechtenstein", Divisa = "CHF", Iso = "LI" },
    new Pais { Id = 113, Nombre = "Sri Lanka", Divisa = "LKR", Iso = "LK" },
    new Pais { Id = 114, Nombre = "Liberia", Divisa = "LRD", Iso = "LR" },
    new Pais { Id = 115, Nombre = "Lesotho", Divisa = "LSL", Iso = "LS" },
    new Pais { Id = 116, Nombre = "Lithuania", Divisa = "EUR", Iso = "LT" },
    new Pais { Id = 117, Nombre = "Luxembourg", Divisa = "EUR", Iso = "LU" },
    new Pais { Id = 118, Nombre = "Latvia", Divisa = "EUR", Iso = "LV" },
    new Pais { Id = 119, Nombre = "Morocco", Divisa = "MAD", Iso = "MA" },
    new Pais { Id = 120, Nombre = "Monaco", Divisa = "EUR", Iso = "MC" },
    new Pais { Id = 121, Nombre = "Moldova", Divisa = "MDL", Iso = "MD" },
    new Pais { Id = 122, Nombre = "Montenegro", Divisa = "EUR", Iso = "ME" },
    new Pais { Id = 123, Nombre = "Saint Martin", Divisa = "EUR", Iso = "MF" },
    new Pais { Id = 124, Nombre = "Madagascar", Divisa = "MGA", Iso = "MG" },
    new Pais { Id = 125, Nombre = "Marshall Islands", Divisa = "USD", Iso = "MH" },
    new Pais { Id = 126, Nombre = "North Macedonia", Divisa = "MKD", Iso = "MK" },
    new Pais { Id = 127, Nombre = "Mali", Divisa = "XOF", Iso = "ML" },
    new Pais { Id = 128, Nombre = "Myanmar", Divisa = "MMK", Iso = "MM" },
    new Pais { Id = 129, Nombre = "Mongolia", Divisa = "MNT", Iso = "MN" },
    new Pais { Id = 130, Nombre = "Macao", Divisa = "MOP", Iso = "MO" },
    new Pais { Id = 131, Nombre = "Northern Mariana Islands", Divisa = "USD", Iso = "MP" },
    new Pais { Id = 132, Nombre = "Martinique", Divisa = "EUR", Iso = "MQ" },
    new Pais { Id = 133, Nombre = "Mauritania", Divisa = "MRU", Iso = "MR" },
    new Pais { Id = 134, Nombre = "Montserrat", Divisa = "XCD", Iso = "MS" },
    new Pais { Id = 135, Nombre = "Malta", Divisa = "EUR", Iso = "MT" },
    new Pais { Id = 136, Nombre = "Mauritius", Divisa = "MUR", Iso = "MU" },
    new Pais { Id = 137, Nombre = "Malawi", Divisa = "MWK", Iso = "MW" },
    new Pais { Id = 138, Nombre = "Mexico", Divisa = "MXN", Iso = "MX" },
    new Pais { Id = 139, Nombre = "Malaysia", Divisa = "MYR", Iso = "MY" },
    new Pais { Id = 140, Nombre = "Mozambique", Divisa = "MZN", Iso = "MZ" },
    new Pais { Id = 141, Nombre = "Namibia", Divisa = "NAD", Iso = "NA" },
    new Pais { Id = 142, Nombre = "New Caledonia", Divisa = "XPF", Iso = "NC" },
    new Pais { Id = 143, Nombre = "Niger", Divisa = "XOF", Iso = "NE" },
    new Pais { Id = 144, Nombre = "Norfolk Island", Divisa = "AUD", Iso = "NF" },
    new Pais { Id = 145, Nombre = "Nigeria", Divisa = "NGN", Iso = "NG" },
    new Pais { Id = 146, Nombre = "Nicaragua", Divisa = "NIO", Iso = "NI" },
    new Pais { Id = 147, Nombre = "Netherlands", Divisa = "EUR", Iso = "NL" },
    new Pais { Id = 148, Nombre = "Norway", Divisa = "NOK", Iso = "NO" },
    new Pais { Id = 149, Nombre = "Nepal", Divisa = "NPR", Iso = "NP" },
    new Pais { Id = 150, Nombre = "Nauru", Divisa = "AUD", Iso = "NR" },
    new Pais { Id = 151, Nombre = "Niue", Divisa = "NZD", Iso = "NU" },
    new Pais { Id = 152, Nombre = "New Zealand", Divisa = "NZD", Iso = "NZ" },
    new Pais { Id = 153, Nombre = "Oman", Divisa = "OMR", Iso = "OM" },
    new Pais { Id = 154, Nombre = "Panama", Divisa = "PAB", Iso = "PA" },
    new Pais { Id = 155, Nombre = "Peru", Divisa = "PEN", Iso = "PE" },
    new Pais { Id = 156, Nombre = "French Polynesia", Divisa = "XPF", Iso = "PF" },
    new Pais { Id = 157, Nombre = "Papua New Guinea", Divisa = "PGK", Iso = "PG" },
    new Pais { Id = 158, Nombre = "Philippines", Divisa = "PHP", Iso = "PH" },
    new Pais { Id = 159, Nombre = "Pakistan", Divisa = "PKR", Iso = "PK" },
    new Pais { Id = 160, Nombre = "Poland", Divisa = "PLN", Iso = "PL" },
    new Pais { Id = 161, Nombre = "Saint Pierre and Miquelon", Divisa = "EUR", Iso = "PM" },
    new Pais { Id = 162, Nombre = "Pitcairn Islands", Divisa = "NZD", Iso = "PN" },
    new Pais { Id = 163, Nombre = "Portugal", Divisa = "EUR", Iso = "PT" },
    new Pais { Id = 164, Nombre = "Palestine", Divisa = "ILS", Iso = "PS" },
    new Pais { Id = 165, Nombre = "Puerto Rico", Divisa = "USD", Iso = "PR" },
    new Pais { Id = 166, Nombre = "Qatar", Divisa = "QAR", Iso = "QA" },
    new Pais { Id = 167, Nombre = "Réunion", Divisa = "EUR", Iso = "RE" },
    new Pais { Id = 168, Nombre = "Romania", Divisa = "RON", Iso = "RO" },
    new Pais { Id = 169, Nombre = "Russia", Divisa = "RUB", Iso = "RU" },
    new Pais { Id = 170, Nombre = "Rwanda", Divisa = "RWF", Iso = "RW" },
    new Pais { Id = 171, Nombre = "Saudi Arabia", Divisa = "SAR", Iso = "SA" },
    new Pais { Id = 172, Nombre = "Solomon Islands", Divisa = "SBD", Iso = "SB" },
    new Pais { Id = 173, Nombre = "Seychelles", Divisa = "SCR", Iso = "SC" },
    new Pais { Id = 174, Nombre = "Sudan", Divisa = "SDG", Iso = "SD" },
    new Pais { Id = 175, Nombre = "Sweden", Divisa = "SEK", Iso = "SE" },
    new Pais { Id = 176, Nombre = "Singapore", Divisa = "SGD", Iso = "SG" },
    new Pais { Id = 177, Nombre = "Saint Helena", Divisa = "SHP", Iso = "SH" },
    new Pais { Id = 178, Nombre = "Slovenia", Divisa = "EUR", Iso = "SI" },
    new Pais { Id = 179, Nombre = "Svalbard and Jan Mayen", Divisa = "NOK", Iso = "SJ" },
    new Pais { Id = 180, Nombre = "Slovakia", Divisa = "EUR", Iso = "SK" },
    new Pais { Id = 181, Nombre = "Sierra Leone", Divisa = "SLL", Iso = "SL" },
    new Pais { Id = 182, Nombre = "San Marino", Divisa = "EUR", Iso = "SM" },
    new Pais { Id = 183, Nombre = "Somalia", Divisa = "SOS", Iso = "SO" },
    new Pais { Id = 184, Nombre = "Suriname", Divisa = "SRD", Iso = "SR" },
    new Pais { Id = 185, Nombre = "South Sudan", Divisa = "SSP", Iso = "SS" },
    new Pais { Id = 186, Nombre = "Sao Tome and Principe", Divisa = "STN", Iso = "ST" },
    new Pais { Id = 187, Nombre = "El Salvador", Divisa = "USD", Iso = "SV" },
    new Pais { Id = 188, Nombre = "Sint Maarten", Divisa = "ANG", Iso = "SX" },
    new Pais { Id = 189, Nombre = "Syria", Divisa = "SYP", Iso = "SY" },
    new Pais { Id = 190, Nombre = "Eswatini", Divisa = "SZL", Iso = "SZ" },
    new Pais { Id = 191, Nombre = "Turks and Caicos Islands", Divisa = "USD", Iso = "TC" },
    new Pais { Id = 192, Nombre = "Chad", Divisa = "XAF", Iso = "TD" },
    new Pais { Id = 193, Nombre = "French Southern Territories", Divisa = "EUR", Iso = "TF" },
    new Pais { Id = 194, Nombre = "Togo", Divisa = "XOF", Iso = "TG" },
    new Pais { Id = 195, Nombre = "Thailand", Divisa = "THB", Iso = "TH" },
    new Pais { Id = 196, Nombre = "Timor-Leste", Divisa = "USD", Iso = "TL" },
    new Pais { Id = 197, Nombre = "Tonga", Divisa = "TOP", Iso = "TO" },
    new Pais { Id = 198, Nombre = "Trinidad and Tobago", Divisa = "TTD", Iso = "TT" },
    new Pais { Id = 199, Nombre = "Tunisia", Divisa = "TND", Iso = "TN" },
    new Pais { Id = 200, Nombre = "Turkey", Divisa = "TRY", Iso = "TR" },
    new Pais { Id = 201, Nombre = "Taiwan", Divisa = "TWD", Iso = "TW" },
    new Pais { Id = 202, Nombre = "Tanzania", Divisa = "TZS", Iso = "TZ" },
    new Pais { Id = 203, Nombre = "Ukraine", Divisa = "UAH", Iso = "UA" },
    new Pais { Id = 204, Nombre = "Uganda", Divisa = "UGX", Iso = "UG" },
    new Pais { Id = 205, Nombre = "United States Minor Outlying Islands", Divisa = "USD", Iso = "UM" },
    new Pais { Id = 206, Nombre = "United States", Divisa = "USD", Iso = "US" },
    new Pais { Id = 207, Nombre = "Uruguay", Divisa = "UYU", Iso = "UY" },
    new Pais { Id = 208, Nombre = "Uzbekistan", Divisa = "UZS", Iso = "UZ" },
    new Pais { Id = 209, Nombre = "Vatican City", Divisa = "EUR", Iso = "VA" },
    new Pais { Id = 210, Nombre = "Saint Vincent and the Grenadines", Divisa = "XCD", Iso = "VC" },
    new Pais { Id = 211, Nombre = "Venezuela", Divisa = "VES", Iso = "VE" },
    new Pais { Id = 212, Nombre = "British Virgin Islands", Divisa = "USD", Iso = "VG" },
    new Pais { Id = 213, Nombre = "United States Virgin Islands", Divisa = "USD", Iso = "VI" },
    new Pais { Id = 214, Nombre = "Vietnam", Divisa = "VND", Iso = "VN" },
    new Pais { Id = 215, Nombre = "Vanuatu", Divisa = "VUV", Iso = "VU" },
    new Pais { Id = 216, Nombre = "Wallis and Futuna", Divisa = "XPF", Iso = "WF" },
    new Pais { Id = 217, Nombre = "Samoa", Divisa = "WST", Iso = "WS" },
    new Pais { Id = 218, Nombre = "Yemen", Divisa = "YER", Iso = "YE" },
    new Pais { Id = 219, Nombre = "South Africa", Divisa = "ZAR", Iso = "ZA" },
    new Pais { Id = 220, Nombre = "Zambia", Divisa = "ZMW", Iso = "ZM" },
    new Pais { Id = 221, Nombre = "Zimbabwe", Divisa = "ZWL", Iso = "ZW" }
            );


            modelBuilder.Entity<Cliente>().HasData(
                new Cliente
                {
                    Id = 1,
                    Nombre = "Juan",
                    Apellido = "Perez",
                    dateOfBirth = new DateTime(1990, 1, 1),
                    PaisId = 1,
                    Empleo = "Delincuente",
                    Email = "amin1@gmail.com"
                },
                new Cliente
                {
                    Id = 2,
                    Nombre = "Maria",
                    Apellido = "Lopez",
                    dateOfBirth = new DateTime(1985, 5, 23),
                    PaisId = 2,
                    Empleo = "Profesor",
                    Email = "amin2@gmail.com"
                },
                new Cliente
                {
                    Id = 3,
                    Nombre = "Carlos",
                    Apellido = "Gomez",
                    dateOfBirth = new DateTime(1978, 11, 12),
                    PaisId = 3,
                    Empleo = "Abogado",
                    Email = "amin3@gmail.com"
                }
            );

            modelBuilder.Entity<Cliente>()
                .HasOne(c => c.Pais)
                .WithMany(p => p.Clientes)
                .HasForeignKey(c => c.PaisId);

            modelBuilder.Entity<VistaClientesPaises>(entity =>
            {
                entity.HasNoKey();
                entity.ToView("VistaClientesPaises");
            });
        }
    }
}
